export interface Tool {
  id: string
  name: string
  description: string
  category: string   // matches ToolCategory.id
  icon: string       // lucide-react component name
  color: string      // category accent hex
  comingSoon: boolean
  route: string
}

export const tools: Tool[] = [
  // ─── PDF Tools ────────────────────────────────────────────────────────────
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce PDF file size without losing quality',
    category: 'pdf',
    icon: 'FileArchive',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/compress-pdf',
  },
  {
    id: 'pdf-converter',
    name: 'PDF Converter',
    description: 'Convert Word, PowerPoint, and Excel to and from PDF',
    category: 'pdf',
    icon: 'RefreshCw',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/pdf-converter',
  },
  {
    id: 'pdf-ocr',
    name: 'PDF OCR',
    description: 'Make text in scanned documents searchable',
    category: 'pdf',
    icon: 'ScanSearch',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/pdf-ocr',
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one document',
    category: 'pdf',
    icon: 'FilePlus2',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/merge-pdf',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Extract pages from your PDF as separate files',
    category: 'pdf',
    icon: 'Scissors',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/split-pdf',
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate one or all pages in your PDF',
    category: 'pdf',
    icon: 'RotateCw',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/rotate-pdf',
  },
  {
    id: 'delete-pages',
    name: 'Delete PDF Pages',
    description: 'Remove pages from your PDF',
    category: 'pdf',
    icon: 'Trash2',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/delete-pages',
  },
  {
    id: 'extract-pages',
    name: 'Extract PDF Pages',
    description: 'Pick only the pages you need',
    category: 'pdf',
    icon: 'FileDown',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/extract-pages',
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    description: 'Rearrange, delete, add pages and rotate your PDFs',
    category: 'pdf',
    icon: 'LayoutDashboard',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/organize-pdf',
  },
  {
    id: 'edit-pdf',
    name: 'Edit PDF',
    description: 'Add text, shapes, images and annotations to your PDF',
    category: 'pdf',
    icon: 'PenLine',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/edit-pdf',
  },
  {
    id: 'redact-pdf',
    name: 'Redact PDF',
    description: 'Permanently black out and destroy sensitive text and images',
    category: 'pdf',
    icon: 'EyeOff',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/redact-pdf',
  },
  {
    id: 'watermark-pdf',
    name: 'Watermark PDF',
    description: 'Add a watermark to your PDFs',
    category: 'pdf',
    icon: 'Stamp',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/watermark-pdf',
  },
  {
    id: 'number-pages',
    name: 'Number Pages',
    description: 'Insert page numbers in PDF with ease',
    category: 'pdf',
    icon: 'Hash',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/number-pages',
  },
  {
    id: 'flatten-pdf',
    name: 'Flatten PDF',
    description: 'Lock form fields and annotations into static, uneditable content',
    category: 'pdf',
    icon: 'Layers',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/flatten-pdf',
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Encrypt your PDF with AES-256 and restrict copying, editing, and printing',
    category: 'pdf',
    icon: 'ShieldCheck',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/protect-pdf',
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password and encryption from your PDF',
    category: 'pdf',
    icon: 'LockOpen',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/unlock-pdf',
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Create an electronic signature and sign your documents',
    category: 'pdf',
    icon: 'PenSquare',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/sign-pdf',
  },
  {
    id: 'pdf-reader',
    name: 'PDF Reader',
    description: 'Display, print, and share PDFs online',
    category: 'pdf',
    icon: 'BookOpen',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/pdf-reader',
  },
  {
    id: 'pdf-annotator',
    name: 'PDF Annotator',
    description: 'Write, draw, and highlight on your PDF',
    category: 'pdf',
    icon: 'Highlighter',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/pdf-annotator',
  },
  {
    id: 'pdf-form-filler',
    name: 'PDF Form Filler',
    description: 'Fill out PDF forms online',
    category: 'pdf',
    icon: 'ClipboardType',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/pdf-form-filler',
  },
  {
    id: 'strip-metadata',
    name: 'Strip PDF Metadata',
    description: 'Reveal and remove hidden author, GPS, software, and revision data from PDFs',
    category: 'pdf',
    icon: 'ShieldOff',
    color: '#e74c3c',
    comingSoon: false,
    route: '/tools/strip-metadata',
  },

  // ─── Convert ──────────────────────────────────────────────────────────────
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDFs to editable Word documents',
    category: 'convert',
    icon: 'FileText',
    color: '#3498db',
    comingSoon: false,
    route: '/tools/pdf-to-word',
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents to PDF files',
    category: 'convert',
    icon: 'FileOutput',
    color: '#3498db',
    comingSoon: false,
    route: '/tools/word-to-pdf',
  },
  {
    id: 'pdf-to-ppt',
    name: 'PDF to PowerPoint',
    description: 'Convert PDFs to editable presentations',
    category: 'convert',
    icon: 'Presentation',
    color: '#3498db',
    comingSoon: false,
    route: '/tools/pdf-to-ppt',
  },
  {
    id: 'ppt-to-pdf',
    name: 'PPT to PDF',
    description: 'Convert PowerPoint presentations to PDF',
    category: 'convert',
    icon: 'FileOutput',
    color: '#3498db',
    comingSoon: false,
    route: '/tools/ppt-to-pdf',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Convert PDFs to editable Excel spreadsheets',
    category: 'convert',
    icon: 'Table',
    color: '#3498db',
    comingSoon: false,
    route: '/tools/pdf-to-excel',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF',
    category: 'convert',
    icon: 'FileSpreadsheet',
    color: '#3498db',
    comingSoon: false,
    route: '/tools/excel-to-pdf',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Save each page as a separate image',
    category: 'convert',
    icon: 'Image',
    color: '#3498db',
    comingSoon: false,
    route: '/tools/pdf-to-jpg',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Transform images (JPG, PNG, BMP, GIF, TIFF) to PDF',
    category: 'convert',
    icon: 'ImagePlus',
    color: '#3498db',
    comingSoon: false,
    route: '/tools/jpg-to-pdf',
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert web pages to PDF documents',
    category: 'convert',
    icon: 'Globe',
    color: '#3498db',
    comingSoon: false,
    route: '/tools/html-to-pdf',
  },
  {
    id: 'markdown-to-pdf',
    name: 'Markdown to PDF',
    description: 'Convert Markdown files to PDF',
    category: 'convert',
    icon: 'FileCode',
    color: '#3498db',
    comingSoon: false,
    route: '/tools/markdown-to-pdf',
  },

  // ─── AI Tools ─────────────────────────────────────────────────────────────
  {
    id: 'ai-pdf-assistant',
    name: 'AI PDF Assistant',
    description: 'Use AI to process and understand your documents',
    category: 'ai',
    icon: 'Bot',
    color: '#9b59b6',
    comingSoon: false,
    route: '/tools/ai-pdf-assistant',
  },
  {
    id: 'chat-with-pdf',
    name: 'Chat with PDF',
    description: 'Ask questions about your PDF and get instant answers',
    category: 'ai',
    icon: 'MessageSquare',
    color: '#9b59b6',
    comingSoon: false,
    route: '/tools/chat-with-pdf',
  },
  {
    id: 'ai-summarizer',
    name: 'AI PDF Summarizer',
    description: 'Get AI-powered summaries of your documents',
    category: 'ai',
    icon: 'Sparkles',
    color: '#9b59b6',
    comingSoon: false,
    route: '/tools/ai-summarizer',
  },
  {
    id: 'translate-pdf',
    name: 'Translate PDF',
    description: 'Translate your PDF to any language',
    category: 'ai',
    icon: 'Languages',
    color: '#9b59b6',
    comingSoon: false,
    route: '/tools/translate-pdf',
  },
  {
    id: 'ai-question-generator',
    name: 'AI Question Generator',
    description: 'Create quizzes and tests from your PDF',
    category: 'ai',
    icon: 'BrainCircuit',
    color: '#9b59b6',
    comingSoon: false,
    route: '/tools/ai-question-generator',
  },

  // ─── Image Tools ──────────────────────────────────────────────────────────
  {
    id: 'image-compress',
    name: 'Compress Images',
    description: 'Reduce image file size',
    category: 'image',
    icon: 'ImageDown',
    color: '#2ecc71',
    comingSoon: false,
    route: '/tools/image-compress',
  },
  {
    id: 'heic-to-jpg',
    name: 'HEIC to JPG',
    description: 'Convert iPhone photos to JPG',
    category: 'image',
    icon: 'Smartphone',
    color: '#2ecc71',
    comingSoon: false,
    route: '/tools/heic-to-jpg',
  },
  {
    id: 'image-resize',
    name: 'Resize Images',
    description: 'Resize photos to any dimension',
    category: 'image',
    icon: 'Maximize2',
    color: '#2ecc71',
    comingSoon: false,
    route: '/tools/image-resize',
  },
  {
    id: 'strip-exif',
    name: 'Strip EXIF',
    description: 'View and remove hidden GPS, camera, and metadata from photos',
    category: 'image',
    icon: 'ShieldX',
    color: '#2ecc71',
    comingSoon: false,
    route: '/tools/strip-exif',
  },
  {
    id: 'image-convert',
    name: 'Image Converter',
    description: 'Convert between PNG, JPG, WebP, BMP, GIF',
    category: 'image',
    icon: 'ArrowLeftRight',
    color: '#2ecc71',
    comingSoon: false,
    route: '/tools/image-convert',
  },
  {
    id: 'png-to-jpg',
    name: 'PNG to JPG',
    description: 'Convert PNG images to JPG format',
    category: 'image',
    icon: 'FileImage',
    color: '#2ecc71',
    comingSoon: false,
    route: '/tools/png-to-jpg',
  },

  // ─── Document Tools ───────────────────────────────────────────────────────
  {
    id: 'ocr-image-to-text',
    name: 'OCR (Image to Text)',
    description: 'Extract text from images using OCR',
    category: 'document',
    icon: 'ScanText',
    color: '#f39c12',
    comingSoon: false,
    route: '/tools/ocr-image-to-text',
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    description: 'Convert between CSV and JSON formats',
    category: 'document',
    icon: 'Braces',
    color: '#f39c12',
    comingSoon: false,
    route: '/tools/csv-to-json',
  },
  {
    id: 'markdown-editor',
    name: 'Markdown Editor',
    description: 'Write and preview Markdown online',
    category: 'document',
    icon: 'FileCode2',
    color: '#f39c12',
    comingSoon: false,
    route: '/tools/markdown-editor',
  },

  // ─── Audio Tools ──────────────────────────────────────────────────────────
  {
    id: 'audio-convert',
    name: 'Audio Converter',
    description: 'Convert between MP3, WAV, OGG, FLAC, M4A, and AAC formats',
    category: 'audio',
    icon: 'Music',
    color: '#1abc9c',
    comingSoon: false,
    route: '/tools/audio-convert',
  },
  {
    id: 'compress-audio',
    name: 'Compress Audio',
    description: 'Reduce audio file size — choose Low, Medium, or High quality',
    category: 'audio',
    icon: 'Volume2',
    color: '#1abc9c',
    comingSoon: false,
    route: '/tools/compress-audio',
  },
  {
    id: 'extract-audio',
    name: 'Extract Audio from Video',
    description: 'Extract the audio track from any video file as MP3',
    category: 'audio',
    icon: 'AudioLines',
    color: '#1abc9c',
    comingSoon: false,
    route: '/tools/extract-audio',
  },
  {
    id: 'strip-audio-metadata',
    name: 'Strip Audio Metadata',
    description: 'Remove ID3 tags, artist, album, and embedded art from MP3, FLAC, and more',
    category: 'audio',
    icon: 'ShieldOff',
    color: '#1abc9c',
    comingSoon: false,
    route: '/tools/strip-audio-metadata',
  },

  // ─── Video Tools ──────────────────────────────────────────────────────────
  {
    id: 'video-convert',
    name: 'Video Converter',
    description: 'Convert between MP4, MKV, MOV, AVI, and WebM formats',
    category: 'video',
    icon: 'Video',
    color: '#e67e22',
    comingSoon: false,
    route: '/tools/video-convert',
  },
  {
    id: 'compress-video',
    name: 'Compress Video',
    description: 'Reduce video file size — choose Low, Medium, or High quality',
    category: 'video',
    icon: 'Film',
    color: '#e67e22',
    comingSoon: false,
    route: '/tools/compress-video',
  },

]

// ─── Lookup maps (built once at module load) ─────────────────────────────────

const _byId = new Map<string, Tool>(tools.map((t) => [t.id, t]))

const _byCategory = tools.reduce<Record<string, Tool[]>>((acc, tool) => {
  ;(acc[tool.category] ??= []).push(tool)
  return acc
}, {})

export function getToolById(id: string): Tool | undefined {
  return _byId.get(id)
}

export function getToolsByCategory(categoryId: string): Tool[] {
  return _byCategory[categoryId] ?? []
}
